### ISSUE TITLE
JOSS REVIEW: Tests

### ISSUE THREAD

**Issue by rbeucher** [ggciag/mandyoc#53]
For now your submission does not have automated tests.
Please consider adding some basic tests. Maybe run tutorials and/or examples.

**Comment by rafaelmds** [comment]
We changed the tests to run a simplified version of examples.

We also configured a workflow (github action) to run the tests automatically using the docker image.

But, since we have a time limit on github actions we will need to adjust the strategy to run the tests to cpu compute time.
We are thinking to use [CircleCI](https://circleci.com/) since it has a higher cpu time quota.

Merged on #68.

**Comment by rbeucher** [comment]
Thanks @rafaelmds.
