### ISSUE TITLE
JOSS REVIEW: Paper

### ISSUE THREAD

**Issue by rbeucher** [ggciag/mandyoc#54]
I think the paper needs a bit of work.

- [ ]  *Statement of Need* There is a lot of codes doing similar things, please state clearly why a new code is needed and what are the new functionalities.
- [ ] *State of the field* is needed. The authors do not describe how this software compares to other commonly-used packages. Consider adding a benchmark for thermochemical convection in parallel... Cite other code/packages.
- [ ] There is a *Mathematics* section that briefly describe Stokes and then the authors list a range of additional functionalities that are not directly related to the title of the paper (Why do you need surface processes, plasticity etc in a thermochemical code?) Please consider rewriting and reorganizing that part. 
- [ ] I am not sure the chosen example is the best to show here. It needs a benchmark model (van Keken would actually be better suited). You can add a figure of a rifting model to show that the code capabilities go beyond thermochemical simulations.
- [ ] The list of references needs to be extended. Some key papers missing there! You should at least cite similar packages that have been published on JOSS.

**Comment by psanan** [comment]
Re several of the points above, I strongly agree that the submission is missing information and citations to position itself relative to other pieces of free and/or open source software which solve similar problems. Strict novelty is [not a requirement for publication](https://joss.readthedocs.io/en/latest/review_criteria.html#an-important-note-about-novel-software-and-citations-of-relevant-work), but it's important for readers to know what differentiates this code from others they may have used or read about, both in terms of the physical problems it solves (in particular, with regards to surface processes) and in terms of the practical usage of the software.

Re point #3,  I think that the [template](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) is a little confusing in mixing literal section headings with section headings that describe how to format things ("Mathematics", "Citations", "Figures") that don't need to be literally included.

Re Point #4, I would argue that the choice of example to include is fine, especially given that the van Keken benchmark is nicely presented in your documentation, this benchmark is presumably identical to the one in `examples/`, and this example does a good job of showing a reproducible experiment quite similar to ones other researchers might want to run with the code.

**Comment by victorsacek** [comment]
The paper was updated following the suggestions of the reviewers:

- The `Statement of Need` was improved, also citing other codes with similar functionalities. 
- The  information related to `Statement of Field` is presented along with `Statement of Need`.
- Additional references were included relative to previous works showing the integration between surface processes and Earth's interior dynamics.
- We preferred to preserve the example of continental rifting because this scenario presents a complex non-linear rheology, what we believe to be an attractive for future users. Other examples of numerical scenarios are presented in the documentation.

Addresses Issue #54.

**Comment by psanan** [comment]
My concerns have been addressed wrt this issue, so consider my comment above "resolved".

**Comment by psanan** [comment]
One further minor comment on the paper (and documentation in general). As far as I can tell, it is never explicitly stated anywhere that this is a 2D-only code, even though in the paper it's compared to codes which support 3D simulations. That's a crucial piece of information for potential users and should be stated clearly. If a potential user needs to perform a 3D simulation, they obviously cannot use Mandyoc and should be directed elsewhere quickly, but otherwise a smaller and more contained (hence potentially easier to understand and modify) 2D-focused code might be just what they're looking for.

**Comment by victorsacek** [comment]
Dear @psanan 
You are correct. Now we explicitly say that Mandyoc is a 2-D code in the JOSS paper.

**Comment by rbeucher** [comment]
Looks OK to me. I am closing this.
